### PR TITLE
Issue/23

### LINKED ISSUE #23: "ACXXX..." String unexplained: Is account ID different from App ID
README confuses users

### PR DESCRIPTION
**Pull request by Deseao**
Fixes #23

### CODE REVIEW

**Review by staylo32 — COMMENTED** [review]
Do you think it would be even more clear to users if we define the accountId and authToken on their own line and use the variables when creating a new client?

**Comment by Deseao** [comment]
> Do you think it would be even more clear to users if we define the accountId and authToken on their own line and use the variables when creating a new client?

Like
`var accountID = 'your_account_id'`
`var authToken = 'your_auth_token'`
or
`var accountID = 'ACXXXXXXXXX'`
`var authToken = 'ldsfkjaslvkjase;lr'`
?

**Review by wajiw — APPROVED** [review]
+1

**Comment by staylo32** [comment]
> > Do you think it would be even more clear to users if we define the accountId and authToken on their own line and use the variables when creating a new client?
> 
> Like
> `var accountID = 'your_account_id'`
> `var authToken = 'your_auth_token'`
> or
> `var accountID = 'ACXXXXXXXXX'`
> `var authToken = 'ldsfkjaslvkjase;lr'`
> ?

Yea, and I think the first one would be better.

**Pull request merged**
